#ifndef HISTOBINDEFS_H__
#define HISTOBINDEFS_H__

#define RUNNUMBERBIN 1
#define CURRENTTIMEBIN 2
#define BORTIMEBIN 3
#define EORTIMEBIN 4
#define LOWRUNEVENTBIN 5
#define EARLYEVENTTIMEBIN 6
#define EARLYEVENTNUMBIN 7

#define NFRAMEWORKBINS 7

#endif /* HISTOBINDEFS_H__ */
